"use client";

import { useMemo, useState } from "react";
import { SiteFooter, SiteHeader } from "../components/InteriorPage";
import { roomInventory } from "./data";

export default function RoomsPage(){
  const [type,setType]=useState("All"); const [capacity,setCapacity]=useState(0); const [sort,setSort]=useState("Recommended"); const [filtersOpen,setFiltersOpen]=useState(false); const [breakfast,setBreakfast]=useState(false);
  const rooms=useMemo(()=>{let list=roomInventory.filter(r=>(type==="All"||r.type===type)&&(!capacity||r.guests>=capacity)&&(!breakfast||r.features.some(f=>f.toLowerCase().includes("breakfast"))));return [...list].sort((a,b)=>sort==="Price: low to high"?a.price-b.price:sort==="Price: high to low"?b.price-a.price:b.rating-a.rating)},[type,capacity,sort,breakfast]);
  return <main className="catalogue-page"><SiteHeader/>
    <section className="catalogue-search"><label><span>LOCATION</span><b>Baan Homes, Shimla</b></label><label><span>CHECK-IN</span><input type="date" defaultValue="2026-08-20"/></label><label><span>CHECK-OUT</span><input type="date" defaultValue="2026-08-22"/></label><label><span>GUESTS</span><select defaultValue="2"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option></select></label><button>Update search</button></section>
    <section className="catalogue-offers"><article><b>Stay 3, save more</b><p>Complimentary breakfast when you book three nights.</p></article><article><b>Book direct benefit</b><p>Best available Baan Homes rate and flexible assistance.</p></article><article><b>Family stay offer</b><p>Save 10% on the Garden or Mountain Family Suite.</p></article></section>
    <div className="catalogue-mobile-bar"><button onClick={()=>setFiltersOpen(true)}>☷ Filters</button><span>{rooms.length} stay options</span><select value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Price: low to high</option><option>Price: high to low</option></select></div>
    <section className="catalogue-layout">
      <aside className={filtersOpen?"catalogue-filters open":"catalogue-filters"}><div className="filter-title"><h2>Filters</h2><button onClick={()=>{setType("All");setCapacity(0);setBreakfast(false)}}>Clear all</button><button className="filter-close" onClick={()=>setFiltersOpen(false)}>×</button></div><div className="filter-group"><h3>Stay type</h3>{["All","Room","Suite","Entire Home"].map(x=><button className={type===x?"selected":""} key={x} onClick={()=>setType(x)}>{x}</button>)}</div><div className="filter-group"><h3>Guests</h3><div className="capacity-row">{[0,2,3,4,5,6].map(x=><button className={capacity===x?"selected":""} key={x} onClick={()=>setCapacity(x)}>{x||"Any"}</button>)}</div></div><div className="filter-group"><h3>Price per night</h3><p>₹5,000 — ₹20,000+</p><input aria-label="Maximum nightly price" type="range" min="5000" max="20000" defaultValue="20000"/></div><div className="filter-group"><h3>Included</h3><label><input type="checkbox" checked={breakfast} onChange={e=>setBreakfast(e.target.checked)}/> Breakfast included</label><label><input type="checkbox"/> Valley view</label><label><input type="checkbox"/> Private outdoor space</label></div><button className="apply-filters" onClick={()=>setFiltersOpen(false)}>Show {rooms.length} options</button></aside>
      <div className="catalogue-results"><div className="catalogue-heading"><div><h1>Rooms at Baan Homes</h1><p>One Shimla home, six thoughtfully designed ways to stay.</p></div><label>Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Price: low to high</option><option>Price: high to low</option></select></label></div><div className="catalogue-banner"><b>Direct booking advantage</b><span>Personal confirmation · Flexible assistance · Call 7018305160</span></div><div className="catalogue-grid">{rooms.map(room=><a href={`/rooms/${room.slug}`} className="catalogue-card" key={room.slug}><div className="catalogue-image" style={{backgroundImage:`url(${room.image})`}}><span>{room.badge}</span><button aria-label="Save room" onClick={e=>e.preventDefault()}>♡</button><i>1 / 3</i></div><div className="catalogue-card-body"><div className="card-title"><h2>{room.name}</h2><b>★ {room.rating}</b></div><p>Baan Homes, Shimla</p><div className="catalogue-facts"><span>{room.guests} guests</span><span>{room.bedrooms} bedroom{room.bedrooms>1?"s":""}</span><span>{room.bathrooms} bath{room.bathrooms>1?"s":""}</span></div><div className="feature-pills">{room.features.slice(0,3).map(f=><span key={f}>{f}</span>)}</div><div className="catalogue-price"><div><del>₹{room.oldPrice.toLocaleString("en-IN")}</del><b>₹{room.price.toLocaleString("en-IN")}</b><small>/ night</small></div><strong>View room →</strong></div><div className="card-offer">✦ Save more when you book direct</div></div></a>)}</div>{rooms.length===0&&<div className="empty-results"><h2>No rooms match those filters.</h2><button onClick={()=>{setType("All");setCapacity(0);setBreakfast(false)}}>Clear filters</button></div>}</div>
    </section><SiteFooter/></main>
}
